"""initial schema

Revision ID: 7db13cef0250
Revises: 
Create Date: 2026-08-06 08:27:49.618171
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db13cef0250'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('warga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=32), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('usia', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=16), nullable=False),
    sa.Column('status_pernikahan', sa.String(length=32), nullable=False),
    sa.Column('jumlah_tanggungan', sa.Integer(), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warga_nik'), ['nik'], unique=True)

    op.create_table('pengajuan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warga_id', sa.Integer(), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warga_id'], ['warga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pengajuan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pengajuan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pengajuan_warga_id'), ['warga_id'], unique=False)

    op.create_table('data_survei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengajuan_id', sa.Integer(), nullable=False),
    sa.Column('pendapatan', sa.Float(), nullable=False),
    sa.Column('status_pekerjaan', sa.String(length=64), nullable=True),
    sa.Column('aset_produktif', sa.Boolean(), nullable=False),
    sa.Column('riwayat_bantuan', sa.Boolean(), nullable=False),
    sa.Column('luas_rumah', sa.Float(), nullable=True),
    sa.Column('jenis_lantai', sa.String(length=32), nullable=True),
    sa.Column('jenis_dinding', sa.String(length=32), nullable=True),
    sa.Column('sumber_air', sa.String(length=32), nullable=True),
    sa.Column('label_historis', sa.Boolean(), nullable=True),
    sa.Column('asal_data', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['pengajuan_id'], ['pengajuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_survei', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_survei_pengajuan_id'), ['pengajuan_id'], unique=True)

    op.create_table('log_pengujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengajuan_id', sa.Integer(), nullable=False),
    sa.Column('waktu_mulai', sa.DateTime(timezone=True), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('durasi_ms', sa.Integer(), nullable=True),
    sa.Column('hasil_sistem', sa.String(length=16), nullable=True),
    sa.Column('hasil_manual_petugas', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['pengajuan_id'], ['pengajuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_pengujian', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_pengujian_pengajuan_id'), ['pengajuan_id'], unique=False)

    op.create_table('prediksi_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengajuan_id', sa.Integer(), nullable=False),
    sa.Column('hasil', sa.String(length=16), nullable=False),
    sa.Column('probabilitas', sa.Float(), nullable=False),
    sa.Column('versi_model', sa.String(length=64), nullable=False),
    sa.Column('waktu_prediksi', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pengajuan_id'], ['pengajuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediksi_ml', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediksi_ml_pengajuan_id'), ['pengajuan_id'], unique=True)

    op.create_table('ranking_topsis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('pengajuan_id', sa.Integer(), nullable=False),
    sa.Column('nilai_preferensi', sa.Float(), nullable=False),
    sa.Column('peringkat', sa.Integer(), nullable=False),
    sa.Column('bobot_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pengajuan_id'], ['pengajuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_topsis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_topsis_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_topsis_pengajuan_id'), ['pengajuan_id'], unique=False)

    op.create_table('teks_naratif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengajuan_id', sa.Integer(), nullable=False),
    sa.Column('sumber', sa.String(length=24), nullable=False),
    sa.Column('isi_teks', sa.Text(), nullable=False),
    sa.Column('label_urgensi_manual', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['pengajuan_id'], ['pengajuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teks_naratif', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teks_naratif_pengajuan_id'), ['pengajuan_id'], unique=False)

    op.create_table('skor_urgensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teks_naratif_id', sa.Integer(), nullable=False),
    sa.Column('skor', sa.Float(), nullable=False),
    sa.Column('versi_model', sa.String(length=64), nullable=False),
    sa.Column('waktu_inference', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teks_naratif_id'], ['teks_naratif.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skor_urgensi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skor_urgensi_teks_naratif_id'), ['teks_naratif_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skor_urgensi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skor_urgensi_teks_naratif_id'))

    op.drop_table('skor_urgensi')
    with op.batch_alter_table('teks_naratif', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teks_naratif_pengajuan_id'))

    op.drop_table('teks_naratif')
    with op.batch_alter_table('ranking_topsis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_topsis_pengajuan_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_topsis_batch_id'))

    op.drop_table('ranking_topsis')
    with op.batch_alter_table('prediksi_ml', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediksi_ml_pengajuan_id'))

    op.drop_table('prediksi_ml')
    with op.batch_alter_table('log_pengujian', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_pengujian_pengajuan_id'))

    op.drop_table('log_pengujian')
    with op.batch_alter_table('data_survei', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_survei_pengajuan_id'))

    op.drop_table('data_survei')
    with op.batch_alter_table('pengajuan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pengajuan_warga_id'))
        batch_op.drop_index(batch_op.f('ix_pengajuan_status'))

    op.drop_table('pengajuan')
    with op.batch_alter_table('warga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warga_nik'))

    op.drop_table('warga')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
